stages:
  - test

unit-scala:
  stage: test
  image: hseeberger/scala-sbt:11.0.10_1.4.9_2.13.5
  script: 
    - apt-get update
    - apt-get install -y csh
    - sbt sbtVersion
    - (cd . ; sbt compile)
    - ./bin/auto-test-scala-on-push.csh

